image: docker:stable

stages:
  - build
  - release

before_script:
  - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $STAGING_REGISTRY

variables:
  STAGING_REGISTRY: 'registry.gitlab.com'
  CONTAINER_IMAGE: ${STAGING_REGISTRY}/BigDataBoutique/${CI_PROJECT_NAME}:commit-${CI_COMMIT_SHA}
  LATEST_IMAGE: ${STAGING_REGISTRY}/BigDataBoutique/${CI_PROJECT_NAME}:latest

build:
  stage: build
  services:
    - name: docker:dind
  script:
    - docker build --squash -t $CONTAINER_IMAGE .
    - docker push $CONTAINER_IMAGE

release:
  stage: release
  services:
    - docker:dind
  before_script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $STAGING_REGISTRY
  script:
    - IMAGE_NAME=${STAGING_REGISTRY}/BigDataBoutique/${CI_PROJECT_NAME}:`date '+%Y-%m-%d-%H%M'`-${CI_COMMIT_SHA:0:9}
    - echo $IMAGE_NAME
    - docker pull $CONTAINER_IMAGE
    - docker tag $CONTAINER_IMAGE $IMAGE_NAME
    - docker push $IMAGE_NAME

    - docker tag $CONTAINER_IMAGE $LATEST_IMAGE
    - docker push $LATEST_IMAGE
  only:
    - master
