image: docker:stable

stages:
  - build
  - release

variables:
  STAGING_REGISTRY: 'registry.gitlab.com'
  CONTAINER_IMAGE: ${STAGING_REGISTRY}/bigdataboutique/${CI_PROJECT_NAME}:commit-${CI_COMMIT_SHA}
  LATEST_IMAGE: ${STAGING_REGISTRY}/bigdataboutique/${CI_PROJECT_NAME}:latest

build:
  stage: build
  services:
    - name: docker:dind
      command: ['--experimental']
  script:
    - docker build --squash -t $CONTAINER_IMAGE .
    - docker push $CONTAINER_IMAGE

release:
  stage: release
  variables:
    GIT_STRATEGY: none
  services:
    - docker:dind
  before_script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $STAGING_REGISTRY
  script:
    - IMAGE_NAME=${STAGING_REGISTRY}/bigdataboutique/${CI_PROJECT_NAME}:`date '+%Y-%m-%d-%H%M'`-${CI_COMMIT_SHA:0:9}
    - docker pull $CONTAINER_IMAGE
    - docker tag $CONTAINER_IMAGE $IMAGE_NAME
    - docker push $IMAGE_NAME

    - docker tag $CONTAINER_IMAGE $LATEST_IMAGE
    - docker push $LATEST_IMAGE
  only:
    - master

dockerhub:
  stage: release
  variables:
    GIT_STRATEGY: none
  services:
    - docker:dind
  before_script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $STAGING_REGISTRY
    - docker login -u $DOCKERHUB_USER -p "$DOCKERHUB_PASSWORD" docker.io
  script:
    - IMAGE_NAME=bigdataboutique/elastalert:${CI_COMMIT_TAG}
    - docker pull $CONTAINER_IMAGE
    - docker tag $CONTAINER_IMAGE $IMAGE_NAME
    - docker push $IMAGE_NAME
    - docker tag $CONTAINER_IMAGE bigdataboutique/elastalert:latest
    - docker push bigdataboutique/elastalert:latest
  only:
    - /^v[\d\.]+$/
    - /^[\d\.]+-v[\d\.]+$/
  except:
    - branches
